### ISSUE TITLE
Very long page render time

### ISSUE THREAD

**Issue by CoreTex** [flownative/flow-google-cloudstorage#10]
If you have many image ressources displayed on one single page. The current behaviour is that when fluid renders the image viewhelper, the cloud connector download the image from the google storage via API. 

You can see the behaviour in the System.log:

Create tmpfile for XXXXXX-HASH1-XXXXXXXXX
Did not import resource as object "XXXXXX-HASH2-XXXXXXXXX" into bucket "my.google.bucket" because that object already existed.

**Comment by kitsunet** [comment]
This has been resolved and found to be a problem in the application implementation.
