### ISSUE TITLE
resources are not published on upload

### ISSUE THREAD

**Issue by Lemmork** [flownative/flow-google-cloudstorage#17]
Hi,

I use a setup similar to the readme with a storage-bucket and target-bucket.
When I upload an asset in the media module the asset will upload to the storage-bucket, but it will not be published in the target-bucket. I need to execute ./flow resource:publish to have the assets in the target-bucket.
Are there any settings I missed?

Versions:
flownative/google-cloudstorage: 5.1.1
neos/neos: 4.3.10
neos/media: 4.3.10

**Comment by Lemmork** [comment]
It seems if this only happens if the target-bucket is the same as the storage bucket and only the keyPrefix is different.

**Comment by robertlemke** [comment]
(wrong issue)

**Comment by paavo** [comment]
Looks like i have the same issue @robertlemke
Also if i crop the image, "create-image-variant" returns 200, but the image is not available until i run `resource:publish`
Any hint how to fix this? 

`Media.asyncThumbnails` is active

@kdambekalns or @robertlemke - we can debug the issue together if this helps!

**Comment by kdambekalns** [comment]
@paavo Could you tell me the versions of Neos/Flow your are using? The issue originally was opened against Neos 4.3 (which is no longer supported), so I wonder what you are using. And I'd like to avoid fixing such an old codebase… 😎

**Comment by paavo** [comment]
Good Morning @kdambekalns 
Sorry for the missing information 🙈 

neos/neos 7.3.6
neos/flow 7.3.6

**Comment by kdambekalns** [comment]
I tried to reproduce this in a site using a two-bucket setup with Neos 7.3.6 and `flownative/google-cloudstorage` 5.3.1 without success.

- When importing an asset in the media module, the original and the thumbnail image appear in both buckets
- Selecting the image in the inspector results in another thumbnail image appearing in both buckets
- Cropping makes a fourth image appear in both buckets

Can you provide the result of `./flow configuration:show --path Neos.Flow.resource`?

**Comment by paavo** [comment]
as @Lemmork posted, te problem only happens in a "one bucket setup" @kdambekalns  🤔 

> It seems if this only happens if the target-bucket is the same as the storage bucket and only the keyPrefix is different.

**Comment by kdambekalns** [comment]
Ah, sorry, I missed that (or rather, thought you were using two buckets). So you have a single bucket… with what prefixes configured?

**Comment by paavo** [comment]
> Ah, sorry, I missed that (or rather, thought you were using two buckets). So you have a single bucket… with what prefixes configured?

I sent you the Configuration via PM. 

Im using the same bucket with prefix `storage` and `target`


```
keyPrefix: storage/
keyPrefix: target/
```

**Comment by kdambekalns** [comment]
The PR fixes that behaviour for me.

@paavo You can test that easily by just changing the line with the `if` directly in `Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Flownative_Google_CloudStorage_GcsTarget.php`

**Comment by kdambekalns** [comment]
Already released with https://github.com/flownative/flow-google-cloudstorage/releases/tag/5.3.2

**Comment by paavo** [comment]
awesome, this works well @kdambekalns 🤩
