### ISSUE TITLE
5.2.0 and upwards should not be compatible with Flow 6.x and below

### ISSUE THREAD

**Issue by DavidSporer** [flownative/flow-google-cloudstorage#25]
If I'm not mistaken, version 5.2.0 and upwards does not handle md5 hashes for resources anymore.
This leads to an error with Flow 6.x and below.
Therefore the version requirement should be neos/flow "^7.0" instead of "^5.2 || ^6.0 || ^7.0" I assume?

**Comment by kdambekalns** [comment]
The commit does not seem to fix all cases of incompatibility, `GcsStorage` still creates `PersistentResource` instances without md5 being set in `importResourceFromContent()`
