### ISSUE TITLE
./flow resource:copy fails with Specified invalid hash to setSha1()

### ISSUE THREAD

**Issue by DavidSporer** [flownative/flow-google-cloudstorage#4]
I'm using Flow 3.3.6 and Version 1.0.1 of this Package.
If I follow the readme, I can add Google Cloud Buckets as Publishing target and publish resources to that.
After I've added the other bucket for storage and use the temporary collection to copy over files, I get the following error:

`Specified invalid hash to setSha1()`

The error that is logged in the Exceptions folder is this one:
`
Exception #1362564220 in line 430 of /data/www/typo3-app/Data/Temporary/Production/SubContextGCloud/Cache/Code/Flow_Object_Classes/Flownativ
e_Google_CloudStorage_GcsStorage.php: Specified invalid hash to setSha1()

24 TYPO3\Flow\Resource\Resource_Original::setSha1(FALSE)
23 Flownative\Google\CloudStorage\GcsStorage_Original::importTemporaryFile("/data/www/typo3-app/Data/Temporary/Production/SubContextGCloud/F
lownative_Google_CloudStorage_587c63397ea62", "tmpNewCollection")
22 Flownative\Google\CloudStorage\GcsStorage_Original::importResource(FALSE, "tmpNewCollection")
21 TYPO3\Flow\Resource\Collection_Original::importResource(FALSE)
20 TYPO3\Flow\Command\ResourceCommandController_Original::copyCommand(TYPO3\Flow\Resource\Collection, TYPO3\Flow\Resource\Collection, TRUE)
19 call_user_func_array(array|2|, array|3|)
18 TYPO3\Flow\Cli\CommandController_Original::callCommandMethod()
17 TYPO3\Flow\Cli\CommandController_Original::processRequest(TYPO3\Flow\Cli\Request, TYPO3\Flow\Cli\Response)
16 TYPO3\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(TYPO3\Flow\Cli\Request, TYPO3\Flow\Cli\Response)
15 TYPO3\Flow\Mvc\Dispatcher_Original::dispatch(TYPO3\Flow\Cli\Request, TYPO3\Flow\Cli\Response)
14 TYPO3\Flow\Cli\CommandRequestHandler::TYPO3\Flow\Cli\{closure}()
13 Closure::__invoke()
12 TYPO3\Flow\Security\Context_Original::withoutAuthorizationChecks(Closure)
11 TYPO3\Flow\Security\Context::withoutAuthorizationChecks(Closure)
10 call_user_func_array(array|2|, array|1|)
9 TYPO3\Flow\Security\Context::Flow_Aop_Proxy_invokeJoinPoint(TYPO3\Flow\Aop\JoinPoint)
8 TYPO3\Flow\Aop\Advice\AdviceChain::proceed(TYPO3\Flow\Aop\JoinPoint)
7 TYPO3\Flow\Session\Aspect\LazyLoadingAspect_Original::callMethodOnOriginalSessionObject(TYPO3\Flow\Aop\JoinPoint)
6 TYPO3\Flow\Aop\Advice\AroundAdvice::invoke(TYPO3\Flow\Aop\JoinPoint)
5 TYPO3\Flow\Aop\Advice\AdviceChain::proceed(TYPO3\Flow\Aop\JoinPoint)
4 TYPO3\Flow\Security\Context::withoutAuthorizationChecks(Closure)
3 TYPO3\Flow\Cli\CommandRequestHandler::handleRequest()
2 TYPO3\Flow\Core\Bootstrap::run()
1 require("/data/www/typo3-app/Packages/Framework/TYPO3.Flow/Scripts/flow.php")
`

My configuration looks like this when this happens:

TYPO3:
  Flow:
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'TYPO3\Flow\Resource\Target\FileSystemSymlinkTarget'
          targetOptions:
            relativeSymlinks: TRUE
            subdivideHashPathSegment: TRUE
        localWebDirectoryStaticResourcesTarget:
          target: 'TYPO3\Flow\Resource\Target\FileSystemSymlinkTarget'
          targetOptions:
            relativeSymlinks: TRUE
      collections:
        tmpNewCollection:
          storage: 'googlePersistentResourcesStorage'
          target: 'googlePersistentResourcesTarget'
      collections:
        persistent:
          target: 'googlePersistentResourcesTarget'
      storages:
        googlePersistentResourcesStorage:
          storage: 'Flownative\Google\CloudStorage\GcsStorage'
          storageOptions:
            bucket: 'storage-passcreator-test'
            keyPrefix: '/dockerized-test/'
      targets:
        googlePersistentResourcesTarget:
          target: 'Flownative\Google\CloudStorage\GcsTarget'
          targetOptions:
            bucket: 'passcreator-test'
            keyPrefix: '/dockerized-test/'
            baseUri: 'http://storage.googleapis.com/passcreator-test/dockerized-test/'

Do you guys have any idea why this happens?
If you need more info, just ping me :-)

Thanks,
David

**Comment by kitsunet** [comment]
Yes, I see what happens, the hash is checked case sensitive with only lower case letters allowed. That needs to be fixed... It's a bug in Flow though.

**Comment by DavidSporer** [comment]
Where exactly does that happen? Maybe I'm able to fix it myself and issue a PR afterwards.

**Comment by robertlemke** [comment]
@DavidSporer looks like on your system the PHP function `sha1_file()` returns a hexadecimal value with uppercase characters - can you confirm this?

```php
<?php
echo sha1_file(__FILE__);`
```

On my mac this displays `c4ea92794524ae8e4029c172ffab05239bff00d1`.

In any case, `setSha1()` in Flow's `PersistentResource` should accept both cases and normalize to lowercase.

**Comment by robertlemke** [comment]
It should be fixed here: https://github.com/neos/flow-development-collection/blob/3.2/TYPO3.Flow/Classes/TYPO3/Flow/Resource/Resource.php#L339 and then upmerged.

**Comment by DavidSporer** [comment]
Thanks for this and sorry that I didn't get back to you guys.
On my system sha1_file returns lowercase characters but the sha1 value that is submitted to the setSha1 function is FALSE which leads to the error.
Need to figure out why that is but thanks for fixing that anyway :-)
