### ISSUE TITLE
Public URLs with invalid spaces.

### ISSUE THREAD

**Issue by cwenzelg** [flownative/flow-google-cloudstorage#6]
return implode('/', array_map('rawurlencode', explode('/', $relativePathAndFilename)));

This part gives problem with the flow resources. Google will mask the masked url again himself. so right now google will give a double masked url while flow will expect the one time masked url.

Till now we handled this problem in our own code. I would love to see that flow itself would handle all resources like this (maybe via a settings option togglable). but right now if only google could storage is doing this but the DB entry of flow stays original we don't get the same public urls!

(Well google sees the % also as a special char he wants to mask again when publishing so that's the problem here)

**Comment by kitsunet** [comment]
We identified this problem at the codesprint. The correct solution would be to NOT encode when generating the object name for the new cloud storage object (so for uploading) but then DO encode when generating the public URI to the resource as Google will encode the space in the object name anyway. So currently a space results in double encoded URIs (which the target doesn't produce), which means a round trip fails.

**Comment by kitsunet** [comment]
Closed by #8 thanks to @cwenzelg
